#!/bin/sh

# TWEAKS 

# Multi-monitor
#bspc monitor eDP1 -d VII VIII IX X
#bspc monitor HDMI-1 -d I II III IV V VI

bspc wm --reorder-monitors HDMI-1 eDP-1

num_monitors="$(xrandr --query | grep ' connected' | wc -l)"
if [ $num_monitors -eq 1 ]; then
  for d in VIII VII VI; do
    bspc desktop -r $d 2>&1 /dev/null || true
  done
  bspc monitor eDP-1 -d I II III IV V VI

else
  xrandr --output HDMI-1 --mode 1920x1080 --primary --auto --left-of eDP-1  
  bspc monitor HDMI-1 -d I II III IV V VI
  bspc monitor eDP-1 -d VII VIII IX X
fi

###########################################################################

# border
bspc config border_width	1
bspc config focused_border_color	\#5f3343
bspc config normal_border_color		\#1a1a19

# etc
bspc config focus_follows_pointer true
bspc config gapless_monocle	true
bspc config split_ratio		0.5
bspc config window_gap		5

# mouse settings
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_modifier mod1

# window rules
bspc rule -a 'Dragon-drop:*' state=floating sticky=on 
bspc rule -a '*:zbar' state=floating focus=on
bspc rule -a 'jetbrains-studio:*:win0' state=floating focus=on
bspc rule -a 'Localsend_app' state=tiled focus=on
bspc rule -a 'discord:discord:*' sticky=on

# autostart
. ~/.config/bspwm/autostart
