# Colors (Kanagawa Dragon)
# Source https//github.com/rebelot/kanagawa.nvim

[colors.primary]
#background = '#181616'
background = '#1c1c1c' # Background color with tmux
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'


[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Beam"

[font]
size = 15.0

[font.normal]
#family = "0xProto Nerd Font"
family = "Inconsolata Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 1.0
padding = { x = 65, y = 0 }
